### ISSUE TITLE
Critical! Bug report: Inventory messed up using MultiverseInventories

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#36]
**Describe the bug**
The plugin doesn't work correctly when multiverse inventories is installed. Items are not given until leaving the lobby, and messing up inventories of the world you leave to.

Also, when you die in the lobby and it stats a new round the items will be gone. So you can't starta  new round or leave cause you don't have the items.

**To Reproduce**
1. Install both plugins.
2. Join with /hs join from world Hub.
You will notice you don't get the lobby items while in the lobby.
3. Leave with /hs leave.
You now have the game items in the world Hub.

**Expected behavior**
You should get the lobby items while in the game, then return to the inventory you had when you leave.

**Screenshots**

**System Info (please complete the following information):**
 - OS: [e.g. Windows/Linux] windows
 - Server Host [e.g. Apex/Custom] custom
 - MC Version [e.g. 1.17/1.18] 1.18.2
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] 1.4.3

**Additional context**
Heres a video showing the bug: https://www.youtube.com/watch?v=Q5OjMWn65ws
Note: This only happens when you join from another world! If I teleport to the world i have my lobby in before I join, it works as it should. I guess you give out the items before the player has teleported to the other world.

**Comment by tylermurphy534** [comment]
Multiverse has created multiple issues in the past, and i'm not suprised its causing issues right now. Ill look into this, but the only solution may be on your end, stay tuned.

**Comment by tylermurphy534** [comment]
Is your lobby in a separate world than you were running the command in? If so I believe its because im giving you the items, then teleporting you to the lobby (which will be in a separate world with a different inv).

I modified the code to teleport you first before doing anything when joining. Hopefully that works.

`Also, when you die in the lobby and it stats a new round the items will be gone. So you can't starta new round or leave cause you don't have the items.`
How are you dying in the lobby, it should be impossible as I cancel ALL damage events. Also I think I fixed the rejoin lobby items missing issue. More multiverse crap lol.

**Comment by tylermurphy534** [comment]
Uploaded 1.4.3 beta containing possible fixes for just the bug fix requests.

**Comment by Nesseley** [comment]
I agree that the problem would be because the items were given before teleporting to the right world. 

world_hub -> /hs join -> world_hideandseek 
And then the exit is set in world_hub again. 

So your fix with changing the time of items given should work :)

I'm dying in the game, sorry. Not the lobby, with pvp mode on and killing the hiders :) I will test the new version and get back to you

**Comment by Nesseley** [comment]
Item not given on join: fixed
Items broken when leaving: fixed
Items not given when found/start of new round: fixed

Amazing plugin and thank you for being such a good dev!
