### ISSUE TITLE
There are some issues with some mc server versions and ProtocolLib

### ISSUE THREAD

**Issue by HIBIKI-1933** [tylermurphy534/KenshinsHideAndSeek#73]
**Describe the bug**
At first, when I tried to run the code after merging the code, it prompted such a problem
![image](https://user-images.githubusercontent.com/58289130/183838694-dbd7d7eb-ee78-4faa-9652-66f4429f6bcc.png)
![image](https://user-images.githubusercontent.com/58289130/183838784-537f60f9-858a-48f8-885a-e84d99dc78db.png)
Then I tried to modify the name of the newly registered team and it worked
I am currently developing some small functions such as footprints, bloodstains, progressive safe area, compass, etc. on your branch code in my spare time, and I noticed that you recently updated the BLOCK HUNT feature, it's awesome! but unfortunately he can't run completely on my server at present and you can reproduce it like this
**To Reproduce**
1.debug or enter a game with block' hunt turned on
2.wait a while and don't move
3.see the error log
When the server's ProtocolLib version is 4.4:
![image](https://user-images.githubusercontent.com/58289130/183848071-ad55956c-145e-4b7f-8da2-6c83935fe215.png)
When 4.7:
![image](https://user-images.githubusercontent.com/58289130/183848149-17b105e5-6964-48ed-bc02-d5e66644be0a.png)

and the materialof the BlockHunt block will disappear at this time
in order to exclude possible interference from my code, these tests were performed on your latest release,I know it might be a problem with ProtocolLib, but got no answer in its github bug report, It's quite possible that updating the server core version will fix this, but I'm wondering if there are other ways to fix it
My English is very very very poor, so the above content is carried out with the help of translation software. If there is any problem with the expression, I hope to understand.By the way, your plugin is awesomeXD

**System Info (please complete the following information):**
 - Server OS: Linux
 - Server Version CatServer-1.12.2
 - MC Version 1.12.2
 - Plugin Version 1.6.0

**Comment by HIBIKI-1933** [comment]
when ProtocolLib version is 4.7:
![image](https://user-images.githubusercontent.com/58289130/183847827-dc016140-e7e4-4a84-a694-2d5b5f3a17b7.png)
This section doesn't seem to display properly

**Comment by tylermurphy534** [comment]
Hello, and those extra features sound cool!

I see that you are using ProtocolLib 4.4 now, but the current version is 4.8, which you can download [here](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0). Please try updating to that version. The reason I think its sending that error is because its reflection methods for NMS are do not work on your current server version with the current plugin version. Try updating and see if it fixes that. The block disappearing bug might also be causes by an old protocollib version.

I think that is the issue because I checked the Protocol History of that packet, and it hasnt changed from 1.8 to 1.19. So there shoudn't be any NoSuchFieldErrors caused by NMS packet changes.

Sincerely,

Tyler Murphy

**Comment by HIBIKI-1933** [comment]
Thank you for your endorsement of my inspiration for your plugin extra features! I just started learning how to develop plugins for minecraft, your plugin is very helpful for my study.
but unfortunately, using the 4.8.0 version of protocolLib also failed to solve this problem. I have previously tried to use the 4.5.1~4.8.0 version of protocolLib to test, and just re-confirmed it again, the problem still exists. This error starts only after the hider stands still for a few seconds and disappears if it starts to move.
There will also be new warnings when protocolLib version is higher than 4.7.0:
![image](https://user-images.githubusercontent.com/58289130/183911380-276635e5-bb47-49c9-8f1e-c228a40683fc.png)
I've seen similar questions in the issues section of protocolLib's github, but they haven't answered them, but some people say that changing the server core version can solve this problem

**Comment by tylermurphy534** [comment]
Im going to have to do some personal testing when Im home later, so Ill look into this

**Comment by tylermurphy534** [comment]
Its possible CatServer is causing your issue. Since ProtocolLib uses java reflection to support multiple java versions, the names of variables and how the server code is decompiled must be EXACT. Its possible that CatServer has a different decompiled variabled names or somethig. Im looking into this rn.

**Comment by tylermurphy534** [comment]
ProtocolLib is built upon the Spigot Mapping for NMS, not Forge mappings. ProtocolLib does NOT support Minecraft Forge for this very reason. and Since CatServer is just Bukkit stapped onto Minecraft Forge, it is technically stull using Forge Mapping for NMS. So this is why im assuming that CatServer is causing the issue.

**Comment by HIBIKI-1933** [comment]
Thank you for your reply!
It seems everyone is busy with work hahaha, I'm just starting to develop MC plugins so I don't have much insight into this issue, if the bug is indeed CatServer related, I'll try to contact the author via social media I've perfected the progressive safe zone feature in my spare time recently, to make it somewhat similar to PUBG, but I found out right away that the map I selected was too big, even with a radius of 1000 blocks, but it's still satisfying to watch the game's content gradually become richer.

**Comment by tylermurphy534** [comment]
Cat Server is unable to fix the issue on their end, its ProtocolLib. ProtocolLib does not support Forge servers for a reason, and thats because the decompiled NMS source is completly different from Bukkit. And ProtocolLib has already stated that they dont intend to support forge, so currently there is nothing that will work. I can try to implement my own reflection for forge servers, but ill see.
