### ISSUE TITLE
Seekers drop items

### ISSUE THREAD

**Issue by Vilsu221** [tylermurphy534/KenshinsHideAndSeek#79]
**Describe the bug**
When disconnecting mid combat, the seeker drops their weapon.

**Screenshots**
![2022-08-17_17 14 39](https://user-images.githubusercontent.com/58680173/185157619-b354a1fd-05dc-446b-abdf-12e68b695393.png)

**System Info (please complete the following information):**
 - OS: [Linux]
 - Server Host [Custom]
 - MC Version [1.19]
 - Plugin Version [1.6.1]

**Comment by Vilsu221** [comment]
Same issue with Hiders

**Comment by tylermurphy534** [comment]
I have no idea why this is happening, and I am unable to replicate it. What plugins do you have installed?

**Comment by Vilsu221** [comment]
![image](https://user-images.githubusercontent.com/58680173/185236559-e9ee6955-579c-430f-986b-46f56c846499.png)

**Comment by tylermurphy534** [comment]
Just like you other post, I an unable to replicate this whatsoever. Players in minecraft should not drop items on disconnect, and players also  don't die since the damage event is always canceled before they ever could. 

I can try implementing a item deletion on drop if the plugin detects its a game item, but im not 100% sure that will work. Just wait for a response stating its pushed to the beta, then you can test that. I would love to test it myself, but again I am unable to replicate this.

**Comment by tylermurphy534** [comment]
Ok. uploaded new build for the 1.6.2 beta. Download it on the actions page.
